name: CI

on: [push, pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Check for scanner changes
        id: scanner-check
        shell: sh
        run: |-
          {
            test -f src/scanner.c && ! git diff --quiet HEAD^ -- "$_" &&
            printf 'changed=true\n' || printf 'changed=false\n'
          } >> "$GITHUB_OUTPUT"
      - name: Fuzz scanner
        uses: tree-sitter/fuzz-action@v4
        if: steps.scanner-check.outputs.changed == 'true'
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: ${{runner.os == 'Linux'}}
      - name: Run parsing tests
        if: ${{runner.os != 'Windows'}}
        run: |
          node --test bindings/node/parsing_test.js
  fuzz:
    name: Fuzz scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check for scanner changes
        id: scanner-check
        shell: sh
        run: |-
          {
            test -f src/scanner.c && ! git diff --quiet HEAD^ -- "$_" &&
            printf 'changed=true\n' || printf 'changed=false\n'
          } >> "$GITHUB_OUTPUT"
      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@v4
        if: steps.scanner-check.outputs.changed == 'true'
