name: Regenerate parser

on:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  regenerate:
    # Switch back to tree-sitter workflow after
    # https://github.com/tree-sitter/workflows/pull/10
    uses: imustafin/workflows/.github/workflows/regenerate.yml@main
    if: >-
      github.actor == 'dependabot[bot]'
